apiVersion: apps/v1
kind: Deployment
metadata:
  name: optimus-hello-world-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: optimus-hello-world-app
  template:
    metadata:
      labels:
        app: optimus-hello-world-app
    spec:
      containers:
      - name: optimus-hello-world
        image: acnprd00.azurecr.io/optimus-hello-world:v1.0
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: optimus-hello-world-app
  namespace: default
spec:
  selector:
    app: optimus-hello-world-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
